apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment-file
  labels:
    app: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx-pod  
  minReadySeconds: 15
  strategy:
      type: RollingUpdate 
      rollingUpdate:
         maxSurge: 1
         maxUnavailable: 0 
  template:
    metadata:
      labels:
        app: my-nginx-pod
    spec:
      containers:
      - name: my-nginx-container
        image: nginx:1.7.9
        ports:
        - containerPort: 80